const ReactionAI =  require('./Components/State/ReactionAI')
const MoleculeFactory = require('./Models/MoleculeFactory')
const VMolecule = require('./Components/Stateless/Views/Molecule')
const m = MoleculeFactory("CC(CC1=CC=CC=C1)NC")
// console.log(VMolecule([m,1]).compressed())
const r = new ReactionAI()
r.synthesise(m)
